
### get all
GET http://localhost:8081/api/v1/subscriptions
###

### get by ID
GET http://localhost:8081/api/v1/subscriptions/1


### create new subscription
POST http://localhost:8081/api/v1/subscriptions
Content-Type: application/json

{
"service_name" : "Tripolus Cringus",
"price": 1500,
"user_id": "60601fee-2bf1-5721-ae6f-7636e79a0c90",
"start_date": "07-2025"
}

### Update subscr.
PUT http://localhost:8081/api/v1/subscriptions/4
Content-Type: application/json

{
  "end_date": "08-2022"
}

### Delete subscr.
DELETE http://localhost:8081/api/v1/subscriptions/5

### calculate
GET http://localhost:8081/api/v1/subscriptions/calculate

###########

### get all
GET https://auth-xfah.onrender.com/api/v1/subscriptions
###

### get by ID
GET https://auth-xfah.onrender.com/api/v1/subscriptions/1


### create new subscription
POST https://auth-xfah.onrender.com/api/v1/subscriptions
Content-Type: application/json

{
  "service_name" : "Tripolus Cringus",
  "price": 1500,
  "user_id": "60601fee-2bf1-5721-ae6f-7636e79a0c90",
  "start_date": "07-2025"
}

### Update subscr.
PUT https://auth-xfah.onrender.com/api/v1/subscriptions/4
Content-Type: application/json

{
  "end_date": "08-2022"
}

### Delete subscr.
DELETE https://auth-xfah.onrender.com/api/v1/subscriptions/5

### calculate
GET https://auth-xfah.onrender.com/api/v1/subscriptions/calculate